### PR TITLE
Initial support for TypeScript

### PR DESCRIPTION
**Pull request by gvarandas**
# What does this PR do?

This PR aims to set up the initial TypeScript support for the project, which includes dependencies, configuration files and the initial migration of a couple of modules as an example.

# How did we accomplish it?

- Added `TypeScript` dependencies (which removed all the warnings from `yarn` (all ✅ now);
- Migrated the `Game` and `Config` modules to TypeScript (`game.tsx` and `config.ts`, respectively);
  - There's still a lot to do in these files but this should be accomplished in follow-up PRs in favour of keeping the scope of this one limited.
- Altered all references to the `Config` object to now target their specific exported modules (mostly `enums` now);
- Changed the failing test for the `<App />` component (which doesn't exist) to now render the `<Game />` component instead.

### CODE REVIEW

**Comment by gvarandas** [comment]
This should be g2g as well.

**Comment by jmwind** [comment]
Thanks, I pulled the branch and sniff tested the game. The game play seems broken for me. I haven't dug, but did the sniff testing work on your end? Maybe it's something with my setup. I can dig if it worked for you.

**Comment by gvarandas** [comment]
Oh, that's unfortunate. I'm going to double-check the branch later today (as I remember the game working on my end) and update this thread.
Sorry about that 😬

**Comment by gvarandas** [comment]
I've figured out what the issue was: I had moved all the content from `Config` to enums, assuming they were never reassigned, which wasn't the case.
I've cleaned up the implementation, leaving the reassigned values in `Config`, while moving the rest to enums, as they're constants. Also left a `// TODO:` as a reminder for refactoring it and moving the last values to their respective enums.
It should be g2g now (I've spent the last hour playing nonstop lol).

**Comment by gvarandas** [comment]
Closing this pending PR. Feel free to reopen in case it's necessary (:

**Pull request closed without merging**
